config/routes.rb
Sample::Application.routes.draw do
  devise_for :authors

  resources :author_repositories

  resources :commits
  resources :authors

  resources :repositories

end

app/models/author.rb
class Author < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :commits
  has_many :repositories, :through => :author_repositories
  has_many :author_repositories
  validates_precence_of :name
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/author_repository.rb
class AuthorRepository < ActiveRecord::Base

end

app/models/commit.rb
class Commit < ActiveRecord::Base
  belongs_to :author
  belongs_to :commit

  after_create :create_author_repository
  def create_author_repository
     AuthorRepository.create(:author => author, :repository => repository)
  end	
end

app/models/repository.rb
class Repository < ActiveRecord::Base
  has_many :authors, :through => :author_repositories
  has_many :commits
  has_many :author_repositories
  validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/author_repositories_controller.rb
class AuthorRepositoriesController < ApplicationController
  # GET /author_repositories
  # GET /author_repositories.xml
  def index
    @author_repositories = AuthorRepository.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @author_repositories }
    end
  end

  # GET /author_repositories/1
  # GET /author_repositories/1.xml
  def show
    @author_repository = AuthorRepository.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @author_repository }
    end
  end

  # GET /author_repositories/new
  # GET /author_repositories/new.xml
  def new
    @author_repository = AuthorRepository.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @author_repository }
    end
  end

  # GET /author_repositories/1/edit
  def edit
    @author_repository = AuthorRepository.find(params[:id])
  end

  # POST /author_repositories
  # POST /author_repositories.xml
  def create
    @author_repository = AuthorRepository.new(params[:author_repository])

    respond_to do |format|
      if @author_repository.save
        format.html { redirect_to(@author_repository, :notice => 'Author repository was successfully created.') }
        format.xml  { render :xml => @author_repository, :status => :created, :location => @author_repository }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @author_repository.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /author_repositories/1
  # PUT /author_repositories/1.xml
  def update
    @author_repository = AuthorRepository.find(params[:id])

    respond_to do |format|
      if @author_repository.update_attributes(params[:author_repository])
        format.html { redirect_to(@author_repository, :notice => 'Author repository was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @author_repository.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /author_repositories/1
  # DELETE /author_repositories/1.xml
  def destroy
    @author_repository = AuthorRepository.find(params[:id])
    @author_repository.destroy

    respond_to do |format|
      format.html { redirect_to(author_repositories_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/commits_controller.rb
class CommitsController < ApplicationController
  # GET /commits
  # GET /commits.xml
  def index
    @commits = Commit.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @commits }
    end
  end

  # GET /commits/1
  # GET /commits/1.xml
  def show
    @commit = Commit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @commit }
    end
  end

  # GET /commits/new
  # GET /commits/new.xml
  def new
    @commit = Commit.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @commit }
    end
  end

  # GET /commits/1/edit
  def edit
    @commit = Commit.find(params[:id])
  end

  # POST /commits
  # POST /commits.xml
  def create
    @commit = Commit.new(params[:commit])

    respond_to do |format|
      if @commit.save
        format.html { redirect_to(@commit, :notice => 'Commit was successfully created.') }
        format.xml  { render :xml => @commit, :status => :created, :location => @commit }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @commit.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /commits/1
  # PUT /commits/1.xml
  def update
    @commit = Commit.find(params[:id])

    respond_to do |format|
      if @commit.update_attributes(params[:commit])
        format.html { redirect_to(@commit, :notice => 'Commit was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @commit.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /commits/1
  # DELETE /commits/1.xml
  def destroy
    @commit = Commit.find(params[:id])
    @commit.destroy

    respond_to do |format|
      format.html { redirect_to(commits_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  # GET /repositories
  # GET /repositories.xml
  def index
    @repositories = Repository.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @repositories }
    end
  end

  # GET /repositories/1
  # GET /repositories/1.xml
  def show
    @repository = Repository.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @repository }
    end
  end

  # GET /repositories/new
  # GET /repositories/new.xml
  def new
    @repository = Repository.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @repository }
    end
  end

  # GET /repositories/1/edit
  def edit
    @repository = Repository.find(params[:id])
  end

  # POST /repositories
  # POST /repositories.xml
  def create
    @repository = Repository.new(params[:repository])

    respond_to do |format|
      if @repository.save
        format.html { redirect_to(@repository, :notice => 'Repository was successfully created.') }
        format.xml  { render :xml => @repository, :status => :created, :location => @repository }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @repository.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /repositories/1
  # PUT /repositories/1.xml
  def update
    @repository = Repository.find(params[:id])

    respond_to do |format|
      if @repository.update_attributes(params[:repository])
        format.html { redirect_to(@repository, :notice => 'Repository was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @repository.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /repositories/1
  # DELETE /repositories/1.xml
  def destroy
    @repository = Repository.find(params[:id])
    @repository.destroy

    respond_to do |format|
      format.html { redirect_to(repositories_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/author_repositories_helper.rb
module AuthorRepositoriesHelper
end

app/helpers/commits_helper.rb
module CommitsHelper
end

app/helpers/repositories_helper.rb
module RepositoriesHelper
end

app/views/author_repositories/_form.html.erb
<%= form_for(@author_repository) do |f| %>
  <% if @author_repository.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author_repository.errors.count, "error") %> prohibited this author_repository from being saved:</h2>

      <ul>
      <% @author_repository.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/author_repositories/edit.html.erb
<h1>Editing author_repository</h1>

<%= render 'form' %>

<%= link_to 'Show', @author_repository %> |
<%= link_to 'Back', author_repositories_path %>

app/views/author_repositories/index.html.erb
<h1>Listing author_repositories</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @author_repositories.each do |author_repository| %>
  <tr>
    <td><%= link_to 'Show', author_repository %></td>
    <td><%= link_to 'Edit', edit_author_repository_path(author_repository) %></td>
    <td><%= link_to 'Destroy', author_repository, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Author repository', new_author_repository_path %>

app/views/author_repositories/new.html.erb
<h1>New author_repository</h1>

<%= render 'form' %>

<%= link_to 'Back', author_repositories_path %>

app/views/author_repositories/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_author_repository_path(@author_repository) %> |
<%= link_to 'Back', author_repositories_path %>

app/views/commits/_form.html.erb
<%= form_for(@commit) do |f| %>
  <% if @commit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@commit.errors.count, "error") %> prohibited this commit from being saved:</h2>

      <ul>
      <% @commit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sha %><br />
    <%= f.text_field :sha %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_field :comment %>
  </div>
  <div class="field">
    <%= f.label :commented_at %><br />
    <%= f.time_select :commented_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/commits/edit.html.erb
<h1>Editing commit</h1>

<%= render 'form' %>

<%= link_to 'Show', @commit %> |
<%= link_to 'Back', commits_path %>

app/views/commits/index.html.erb
<h1>Listing commits</h1>

<table>
  <tr>
    <th>Sha</th>
    <th>Comment</th>
    <th>Commented at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @commits.each do |commit| %>
  <tr>
    <td><%= commit.sha %></td>
    <td><%= commit.comment %></td>
    <td><%= commit.commented_at %></td>
    <td><%= link_to 'Show', commit %></td>
    <td><%= link_to 'Edit', edit_commit_path(commit) %></td>
    <td><%= link_to 'Destroy', commit, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Commit', new_commit_path %>

app/views/commits/new.html.erb
<h1>New commit</h1>

<%= render 'form' %>

<%= link_to 'Back', commits_path %>

app/views/commits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Sha:</b>
  <%= @commit.sha %>
</p>

<p>
  <b>Comment:</b>
  <%= @commit.comment %>
</p>

<p>
  <b>Commented at:</b>
  <%= @commit.commented_at %>
</p>


<%= link_to 'Edit', edit_commit_path(@commit) %> |
<%= link_to 'Back', commits_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sample</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/repositories/_form.html.erb
<%= form_for(@repository) do |f| %>
  <% if @repository.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@repository.errors.count, "error") %> prohibited this repository from being saved:</h2>

      <ul>
      <% @repository.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :repo_type %><br />
    <%= f.text_field :repo_type %>
  </div>
  <div class="field">
    <%= f.label :path %><br />
    <%= f.text_field :path %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/repositories/edit.html.erb
<h1>Editing repository</h1>

<%= render 'form' %>

<%= link_to 'Show', @repository %> |
<%= link_to 'Back', repositories_path %>

app/views/repositories/index.html.erb
<h1>Listing repositories</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Repo type</th>
    <th>Path</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @repositories.each do |repository| %>
  <tr>
    <td><%= repository.name %></td>
    <td><%= repository.repo_type %></td>
    <td><%= repository.path %></td>
    <td><%= link_to 'Show', repository %></td>
    <td><%= link_to 'Edit', edit_repository_path(repository) %></td>
    <td><%= link_to 'Destroy', repository, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Repository', new_repository_path %>

app/views/repositories/new.html.erb
<h1>New repository</h1>

<%= render 'form' %>

<%= link_to 'Back', repositories_path %>

app/views/repositories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @repository.name %>
</p>

<p>
  <b>Repo type:</b>
  <%= @repository.repo_type %>
</p>

<p>
  <b>Path:</b>
  <%= @repository.path %>
</p>


<%= link_to 'Edit', edit_repository_path(@repository) %> |
<%= link_to 'Back', repositories_path %>